// <auto-generated />
using Jewelry_Blazor_App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jewelry_Blazor_App.Migrations
{
    [DbContext(typeof(JewelryDbContext))]
    partial class JewelryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Jewelry_Blazor_App.Jewelry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JewelryStoreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("JewelryStoreId");

                    b.ToTable("Jewelries");
                });

            modelBuilder.Entity("Jewelry_Blazor_App.JewelryStore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Jewelry_Blazor_App.Jewelry", b =>
                {
                    b.HasOne("Jewelry_Blazor_App.JewelryStore", "JewelryStore")
                        .WithMany("JewelryList")
                        .HasForeignKey("JewelryStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JewelryStore");
                });

            modelBuilder.Entity("Jewelry_Blazor_App.JewelryStore", b =>
                {
                    b.Navigation("JewelryList");
                });
#pragma warning restore 612, 618
        }
    }
}
